import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import useSmoothNumber from "../hooks/useSmoothNumber";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { number, move } = useSmoothNumber();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative h-screen w-screen overflow-hidden bg-black">
        <div
          style={{
            transform: `translate(${-number.w}px, ${-number.h}px)`,
          }}
          className="h-screen4 w-screen4 text-white transition-all duration-1000"
        >
          <button onClick={() => move({ w: 896, h: 896 })}>click</button>
          <div className="absolute top-ex12 left-ex12 h-screen w-screen p-10">
            <div className="h-full rounded-lg border p-10">
              <button onClick={() => move({ w: 0, h: 0 })}>click</button>
            </div>
          </div>
        </div>
        <canvas className="h-screen4 w-screen4"></canvas>
      </div>
    </>
  );
};

export default Home;
